### ISSUE TITLE
A Frame of Ore Smelters appear briefly after selling them

### ISSUE THREAD

**Issue by WilliamWeberBerrutti** [OpenHV/OpenHV#1125]

**Comment by OcelotWalrus** [comment]
We need a new condition to check if the building is being sold.

```yaml
	WithIdleAnimation:
		Interval: 40
		RequiresCondition: !build-incomplete && !disabled && !burning
```
