### ISSUE TITLE
Walls/Gates need to be disabled for first 2 missions

### ISSUE THREAD

**Issue by Dzierzan** [OpenHV/OpenHV#477]
When they are disabled, the game crashes.

```
BARRIER:
    Buildable:
        Prerequisites: ~disabled

^GATE:
    Buildable:
        Prerequisites: ~disabled
```

[exception-2021-12-20T181408Z.log](https://github.com/OpenHV/OpenHV/files/7776888/exception-2021-12-20T181408Z.log)
